---
title: "Section 4. Simulation"
author: "Seonjoo Lee"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(dplyr)
library(ggplot2)
library(gridExtra)
library(ggthemes)
library(reshape2)
```

# 1. Simulation 1 Visualization
```{r}
rm(list=ls())
filelist=list.files('sim1',pattern='.Rdat', full.names=TRUE)
for (x in filelist){
#  print(x)
  load(x)
}

B=100
tpr.dat=c()
err.dat=c()

for (V in c(400,800)){
  for( n in c(100,300)){
    print(c(n,V))
    obs=NA
    eval(parse(text=paste("obs<-exists('z_n",n,"_V",V,"')",sep='')))
    
    if (obs==TRUE){
      eval(parse(text=paste("re=do.call(cbind,lapply(z_n",n,"_V",V,",
                          function(obj){try(as.matrix(obj$fit$medest)[, min(which(obj$fit$alpha== obj$cvfit$cv.alpha))])}))",sep="")))
      re=re[,apply(re,2,function(x)all(is.na(x)))==FALSE]
      tpr=apply(re[1:3,],1,function(x)sum(x!=0))/B
      fdr=apply(re[-c(1:3),],2,function(x)sum(x!=0))/(V-3)
      err=(apply(re[-c(1:3),],2,function(x)sum(x!=0)) + apply(re[c(1:3),],2,function(x)sum(x==0)))/V
      err.dat=rbind(err.dat,data.frame(n=n,v=V,run=1:ncol(re),fdr=fdr, err=err))
      tpr.dat=rbind(tpr.dat,data.frame(n=n,v=V,r=c('0.5','0.4','0.3'), tpr=tpr))
    }
  }
}

## p-value based screening
tpr.dat.p=c()
err.dat.p=c()

for (V in c(400,800)){
  for( n in c(100,300)){
    print(c(n,V))
    eval(parse(text=paste("re=do.call(cbind,lapply(z_n",n,"_V",V,",function(obs){selected=matrix(0,V,4);selected[obs$xindx_p2,1]<-1;selected[obs$xindx_p1,2]<-1;selected[obs$xindx_p05,3]<-1;selected[obs$xindx_padjust,4]<-1;return(selected)}))",sep="")))
      tpr.p=cbind(
      apply(re[1:3,(1:B)*4 -3],1,function(x)sum(x!=0))/B,
      apply(re[1:3,(1:B)*4 -2],1,function(x)sum(x!=0))/B,
      apply(re[1:3,(1:B)*4 -1],1,function(x)sum(x!=0))/B,
      apply(re[1:3,(1:B)*4],1,function(x)sum(x!=0))/B)
      
      fdr.p=cbind(
      apply(re[-c(1:3),(1:B)*4 -3],2,function(x)sum(x!=0))/B,
      apply(re[-c(1:3),(1:B)*4 -2],2,function(x)sum(x!=0))/B,
      apply(re[-c(1:3),(1:B)*4 -1],2,function(x)sum(x!=0))/B,
      apply(re[-c(1:3),(1:B)*4],2,function(x)sum(x!=0))/B)
      
      tmp1=data.frame(n=n,v=V,run=1:B,fdr=fdr.p)
      names(tmp1)[4:7]<-c('p2','p1','p05','padjust')
      tmp2=data.frame(n=n,v=V,r=c('0.5','0.4','0.3'), tpr=tpr.p)
      names(tmp2)[4:7]<-c('p2','p1','p05','padjust')
      
      err.dat.p=rbind(err.dat.p,tmp1)
      tpr.dat.p=rbind(tpr.dat.p,tmp2)
  }
}
```

```{r,fig.width=7,fig.height=8}
fig1.tpr<-ggplot(rbind(melt(tpr.dat.p,id=c('n','v','r')),
             data.frame(tpr.dat[,1:3],variable='SM',value=tpr.dat[,4])) %>% 
         mutate(r=factor(r), n=factor(n), value=value*100, v=paste('V=',v,sep=''),
                Method=factor(variable, labels=c('p<0.2','p<0.1','p<0.05','B-H', 'SM'))),
       aes(x=n,y=value,colour=Method,group=Method))+
  geom_point()+geom_line()+facet_grid(v~r) +
  ylab('True positive rate (%)') +xlab('Sample size (N)') +ylim(c(0,100)) +
  theme_bw() + 
  theme(legend.position='top', plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text = element_text(size = 12, family = "Tahoma"),
        axis.title = element_text(face="bold"),
        axis.text.x=element_text(size = 11)) +
  ggtitle('(a) True positive rates ')


fig1.fdr<-ggplot(rbind(melt(err.dat.p,id=c('n','v','run')),
             data.frame(err.dat[,c(1:3)],variable='SM',value=err.dat[,4]))%>% 
               mutate(n=factor(n), value=value*100, v=paste('V=',v,sep=''), 
                      Method=factor(variable, labels=c('p<0.2','p<0.1','p<0.05','B-H','SM'))),
       aes(x=n,y=value,fill=Method))+geom_boxplot()+facet_grid(v~.) + 
  ylab('False positive rate (%)') +xlab('Sample size (N)') +ylim(c(0,80)) +
  theme_bw() + 
  theme(legend.position='top', plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text = element_text(size = 12, family = "Tahoma"),
        axis.title = element_text(face="bold"),
        axis.text.x=element_text(size = 11)) +
  ggtitle('(b) False positive rates ')

grid.arrange(fig1.tpr,fig1.fdr, nrow=2)

png('sim1_figure.png',width=2100,height=2400,res=300)
grid.arrange(fig1.tpr,fig1.fdr, nrow=2)
dev.off()
```


# 2. Simulation 2 (Section 3.2) Visualization
```{r}
rm(list=ls())
filelist=list.files('sim3',pattern='.Rdat', full.names=TRUE)
for (x in filelist){
#  print(x)
  load(x)
}

B=100
tpr.dat=c()
err.dat=c()

for (V in c(400,800)){
  for( n in c(100,300)){
    print(c(n,V))
    obs=NA
    eval(parse(text=paste("obs<-exists('z_n",n,"_V",V,"')",sep='')))
    
    if (obs==TRUE){
      eval(parse(text=paste("re=do.call(cbind,lapply(z_n",n,"_V",V,",
                          function(obj){try(as.matrix(obj$fit$medest)[, min(which(obj$fit$alpha== obj$cvfit$cv.alpha))])}))",sep="")))
      re=re[,apply(re,2,function(x)all(is.na(x)))==FALSE]
      tpr=apply(re[1:3,],1,function(x)sum(x!=0))/B
      fdr=apply(re[-c(1:3),],2,function(x)sum(x!=0))/(V-3)
      err=(apply(re[-c(1:3),],2,function(x)sum(x!=0)) + apply(re[c(1:3),],2,function(x)sum(x==0)))/V
      err.dat=rbind(err.dat,data.frame(n=n,v=V,run=1:ncol(re),fdr=fdr, err=err))
      tpr.dat=rbind(tpr.dat,data.frame(n=n,v=V,r=c('M1','M2','M3'), tpr=tpr))
    }
  }
}

## p-value based screening
tpr.dat.p=c()
err.dat.p=c()

for (V in c(400,800)){
  for( n in c(100,300)){
    print(c(n,V))
    eval(parse(text=paste("re=do.call(cbind,lapply(z_n",n,"_V",V,",function(obs){selected=matrix(0,V,4);selected[obs$xindx_p2,1]<-1;selected[obs$xindx_p1,2]<-1;selected[obs$xindx_p05,3]<-1;selected[obs$xindx_padjust,4]<-1;return(selected)}))",sep="")))
      tpr.p=cbind(
      apply(re[1:3,(1:B)*4 -3],1,function(x)sum(x!=0))/B,
      apply(re[1:3,(1:B)*4 -2],1,function(x)sum(x!=0))/B,
      apply(re[1:3,(1:B)*4 -1],1,function(x)sum(x!=0))/B,
      apply(re[1:3,(1:B)*4],1,function(x)sum(x!=0))/B)
      
      fdr.p=cbind(
      apply(re[-c(1:3),(1:B)*4 -3],2,function(x)sum(x!=0))/B,
      apply(re[-c(1:3),(1:B)*4 -2],2,function(x)sum(x!=0))/B,
      apply(re[-c(1:3),(1:B)*4 -1],2,function(x)sum(x!=0))/B,
      apply(re[-c(1:3),(1:B)*4],2,function(x)sum(x!=0))/B)
      
      tmp1=data.frame(n=n,v=V,run=1:B,fdr=fdr.p)
      names(tmp1)[4:7]<-c('p2','p1','p05','padjust')
      tmp2=data.frame(n=n,v=V,r=c('M1','M2','M3'), tpr=tpr.p)
      names(tmp2)[4:7]<-c('p2','p1','p05','padjust')
      
      err.dat.p=rbind(err.dat.p,tmp1)
      tpr.dat.p=rbind(tpr.dat.p,tmp2)
  }
}
```

```{r,fig.width=7,fig.height=8}
fig3.tpr<-ggplot(rbind(melt(tpr.dat.p,id=c('n','v','r')),
             data.frame(tpr.dat[,1:3],variable='SM',value=tpr.dat[,4])) %>% 
         mutate(r=factor(r), n=factor(n), value=value*100, v=paste('V=',v,sep=''),
                Method=factor(variable, labels=c('p<0.2','p<0.1','p<0.05','B-H', 'SM'))),
       aes(x=n,y=value,colour=Method,group=Method))+
  geom_point()+geom_line()+facet_grid(v~r) +
  ylab('True positive rate (%)') +xlab('Sample size (N)') +ylim(c(0,100)) +
  theme_bw() + 
  theme(legend.position='top', plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text = element_text(size = 12, family = "Tahoma"),
        axis.title = element_text(face="bold"),
        axis.text.x=element_text(size = 11)) +
  ggtitle('(a) True positive rates ')


fig3.fdr<-ggplot(rbind(melt(err.dat.p,id=c('n','v','run')),
             data.frame(err.dat[,c(1:3)],variable='SM',value=err.dat[,4]))%>% 
               mutate(n=factor(n), value=value*100, v=paste('V=',v,sep=''), 
                      Method=factor(variable, labels=c('p<0.2','p<0.1','p<0.05','B-H','SM'))),
       aes(x=n,y=value,fill=Method))+geom_boxplot()+facet_grid(v~.) + 
  ylab('False positive rate (%)') +xlab('Sample size (N)') +ylim(c(0,80)) +
  theme_bw() + 
  theme(legend.position='top', plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text = element_text(size = 12, family = "Tahoma"),
        axis.title = element_text(face="bold"),
        axis.text.x=element_text(size = 11)) +
  ggtitle('(b) False positive rates ')

grid.arrange(fig3.tpr,fig3.fdr, nrow=2)

png('sim3_figure.png',width=2100,height=2400,res=300)
grid.arrange(fig3.tpr,fig3.fdr, nrow=2)
dev.off()
```


# 3. Simulation 3 (Section 3.3) Visualization 
```{r}
rm(list=ls())
filelist=list.files('sim2',pattern='.Rdata', full.names=TRUE)
for (x in filelist){
#  print(x)
  load(x)
}
B=100
tpr.dat=c()
err.dat=c()

for (V in c(400,800)){
  for( n in c(100,300)){
    print(c(n,V))
    obs=NA
    eval(parse(text=paste("obs<-exists('z_n",n,"_V",V,"')",sep='')))
    
    if (obs==TRUE){
      eval(parse(text=paste("re=do.call(cbind,lapply(z_n",n,"_V",V,",
                          function(obj){try(as.matrix(obj$fit$medest)[, min(which(obj$fit$alpha== obj$cvfit$cv.alpha))])}))",sep="")))
      re=re[,apply(re,2,function(x)all(is.na(x)))==FALSE]
      tpr=apply(re[1:3,],1,function(x)sum(x!=0))/B
      fdr=apply(re[-c(1:3),],2,function(x)sum(x!=0))/(V-3)
      err=(apply(re[-c(1:3),],2,function(x)sum(x!=0)) + apply(re[c(1:3),],2,function(x)sum(x==0)))/V
      err.dat=rbind(err.dat,data.frame(n=n,v=V,run=1:ncol(re),fdr=fdr, err=err))
      tpr.dat=rbind(tpr.dat,data.frame(n=n,v=V,r=c('0.5','0.4','0.3'), tpr=tpr))
    }
  }
}

## p-value based screening
tpr.dat.p=c()
err.dat.p=c()

for (V in c(400,800)){
  for( n in c(100,300)){
    print(c(n,V))
    eval(parse(text=paste("re=do.call(cbind,lapply(z_n",n,"_V",V,",function(obs){selected=matrix(0,V,4);selected[obs$xindx_p2,1]<-1;selected[obs$xindx_p1,2]<-1;selected[obs$xindx_p05,3]<-1;selected[obs$xindx_padjust,4]<-1;return(selected)}))",sep="")))
      tpr.p=cbind(
      apply(re[1:3,(1:B)*4 -3],1,function(x)sum(x!=0))/B,
      apply(re[1:3,(1:B)*4 -2],1,function(x)sum(x!=0))/B,
      apply(re[1:3,(1:B)*4 -1],1,function(x)sum(x!=0))/B,
      apply(re[1:3,(1:B)*4],1,function(x)sum(x!=0))/B)
      
      fdr.p=cbind(
      apply(re[-c(1:3),(1:B)*4 -3],2,function(x)sum(x!=0))/B,
      apply(re[-c(1:3),(1:B)*4 -2],2,function(x)sum(x!=0))/B,
      apply(re[-c(1:3),(1:B)*4 -1],2,function(x)sum(x!=0))/B,
      apply(re[-c(1:3),(1:B)*4],2,function(x)sum(x!=0))/B)
      
      tmp1=data.frame(n=n,v=V,run=1:B,fdr=fdr.p)
      names(tmp1)[4:7]<-c('p2','p1','p05','padjust')
      tmp2=data.frame(n=n,v=V,r=c('0.5','0.4','0.3'), tpr=tpr.p)
      names(tmp2)[4:7]<-c('p2','p1','p05','padjust')
      
      err.dat.p=rbind(err.dat.p,tmp1)
      tpr.dat.p=rbind(tpr.dat.p,tmp2)
  }
}
```

```{r,fig.width=7,fig.height=8}
fig2.tpr<-ggplot(rbind(melt(tpr.dat.p,id=c('n','v','r')),
             data.frame(tpr.dat[,1:3],variable='SM',value=tpr.dat[,4])) %>% 
         mutate(r=factor(r), n=factor(n), value=value*100, v=paste('V=',v,sep=''),
                Method=factor(variable, labels=c('p<0.2','p<0.1','p<0.05','B-H', 'SM'))),
       aes(x=n,y=value,colour=Method,group=Method))+
  geom_point()+geom_line()+facet_grid(v~r) +
  ylab('True positive rate (%)') +xlab('Sample size (N)') +ylim(c(0,100)) +
  theme_bw() + 
  theme(legend.position='top', plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text = element_text(size = 12, family = "Tahoma"),
        axis.title = element_text(face="bold"),
        axis.text.x=element_text(size = 11)) +
  ggtitle('(a) True positive rates ')


fig2.fdr<-ggplot(rbind(melt(err.dat.p,id=c('n','v','run')),
             data.frame(err.dat[,c(1:3)],variable='SM',value=err.dat[,4]))%>% 
               mutate(n=factor(n), value=value*100, v=paste('V=',v,sep=''), 
                      Method=factor(variable, labels=c('p<0.2','p<0.1','p<0.05','B-H','SM'))),
       aes(x=n,y=value,fill=Method))+geom_boxplot()+facet_grid(v~.) + 
  ylab('False positive rate (%)') +xlab('Sample size (N)') +ylim(c(0,80)) +
  theme_bw() + 
  theme(legend.position='top', plot.title = element_text(size = 14, family = "Tahoma", face = "bold"),
        text = element_text(size = 12, family = "Tahoma"),
        axis.title = element_text(face="bold"),
        axis.text.x=element_text(size = 11)) +
  ggtitle('(b) False positive rates ')

grid.arrange(fig2.tpr,fig2.fdr, nrow=2)

png('sim2_figure.png',width=2100,height=2400,res=300)
grid.arrange(fig2.tpr,fig2.fdr, nrow=2)
dev.off()
```
